/*
* This header is generated by classdump-dyld 1.0
* on Thursday, December 22, 2016 at 6:11:37 PM Eastern European Standard Time
* Operating System: Version 10.1.1 (Build 14B100)
* Image Source: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@interface UNUserNotificationServiceConnection : NSObject 
-(void)addObserver:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)didReceiveDeviceToken:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)invalidateTokenForRemoteNotificationsForBundleIdentifier:(id)arg1 ;
-(void)requestAuthorizationWithOptions:(unsigned long long)arg1 forBundleIdentifier:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)removeObserver:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)_queue_didReceiveDeviceToken:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)didChangePendingNotificationRequests:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)didDeliverNotifications:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)setObservingUserNotifications:(BOOL)arg1 forBundleIdentifier:(id)arg2 ;
-(void)getNotificationSettingsForBundleIdentifier:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
-(void)getNotificationCategoriesForBundleIdentifier:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
-(void)setNotificationCategories:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)addNotificationRequest:(id)arg1 forBundleIdentifier:(id)arg2 withCompletionHandler:(/*^block*/id)arg3 ;
-(void)addNotificationRequests:(id)arg1 forBundleIdentifier:(id)arg2 withCompletionHandler:(/*^block*/id)arg3 ;
-(void)setNotificationRequests:(id)arg1 forBundleIdentifier:(id)arg2 withCompletionHandler:(/*^block*/id)arg3 ;
-(void)removePendingNotificationRequestsWithIdentifiers:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)removeSimilarNotificationRequests:(id)arg1 forBundleIdentifier:(id)arg2 withCompletionHandler:(/*^block*/id)arg3 ;
-(void)removeAllPendingNotificationRequestsForBundleIdentifier:(id)arg1 ;
-(void)getDeliveredNotificationsForBundleIdentifier:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
-(void)removeDeliveredNotificationsWithIdentifiers:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)removeAllDeliveredNotificationsForBundleIdentifier:(id)arg1 ;
-(void)requestTokenForRemoteNotificationsForBundleIdentifier:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
-(void)getAllowsRemoteNotificationsForBundleIdentifier:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
@end

@interface UNNotificationTrigger : NSObject 
@property (nonatomic,readonly) BOOL repeats;              //@synthesize repeats=_repeats - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)_init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)repeats;
-(id)nextTriggerDateAfterDate:(id)arg1 withRequestedDate:(id)arg2 ;
-(double)_retroactiveTriggerHysteresis;
-(id)_initWithRepeats:(BOOL)arg1 ;
-(id)nextTriggerDate;
-(BOOL)willTriggerAfterDate:(id)arg1 withRequestedDate:(id)arg2 ;
-(id)nextTriggerDateAfterLastTriggerDate:(id)arg1 withRequestedDate:(id)arg2 ;
@end

@interface UNNotificationSound : NSObject
@property (nonatomic,readonly) long long alertType;                                            //@synthesize alertType=_alertType - In the implementation block
@property (nonatomic,copy,readonly) NSString * alertTopic;                                     //@synthesize alertTopic=_alertTopic - In the implementation block
@property (nonatomic,copy,readonly) NSString * audioCategory;                                  //@synthesize audioCategory=_audioCategory - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * audioVolume;                                    //@synthesize audioVolume=_audioVolume - In the implementation block
@property (nonatomic,readonly) double maximumDuration;                                         //@synthesize maximumDuration=_maximumDuration - In the implementation block
@property (nonatomic,readonly) BOOL shouldIgnoreRingerSwitch;                                  //@synthesize shouldIgnoreRingerSwitch=_shouldIgnoreRingerSwitch - In the implementation block
@property (nonatomic,readonly) BOOL shouldRepeat;                                              //@synthesize shouldRepeat=_shouldRepeat - In the implementation block
@property (nonatomic,copy,readonly) NSString * toneFileName;                                   //@synthesize toneFileName=_toneFileName - In the implementation block
@property (nonatomic,copy,readonly) NSString * toneIdentifier;                                 //@synthesize toneIdentifier=_toneIdentifier - In the implementation block
@property (nonatomic,readonly) unsigned long long toneMediaLibraryItemIdentifier;              //@synthesize toneMediaLibraryItemIdentifier=_toneMediaLibraryItemIdentifier - In the implementation block
@property (nonatomic,copy,readonly) NSString * vibrationIdentifier;                            //@synthesize vibrationIdentifier=_vibrationIdentifier - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * vibrationPattern;                           //@synthesize vibrationPattern=_vibrationPattern - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)soundWithAlertType:(long long)arg1 ;
+(id)_soundWithAlertType:(long long)arg1 toneFileName:(id)arg2 ;
+(id)soundNamed:(id)arg1 ;
+(id)defaultSound;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSNumber *)audioVolume;
-(NSString *)vibrationIdentifier;
-(unsigned long long)toneMediaLibraryItemIdentifier;
-(NSString *)toneIdentifier;
-(NSString *)toneFileName;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(double)maximumDuration;
-(NSDictionary *)vibrationPattern;
-(long long)alertType;
-(BOOL)shouldIgnoreRingerSwitch;
-(BOOL)shouldRepeat;
-(NSString *)audioCategory;
-(id)_initWithAlertType:(long long)arg1 alertTopic:(id)arg2 audioCategory:(id)arg3 audioVolume:(id)arg4 maximumDuration:(double)arg5 shouldIgnoreRingerSwitch:(BOOL)arg6 shouldRepeat:(BOOL)arg7 toneFileName:(id)arg8 toneIdentifier:(id)arg9 toneMediaLibraryItemIdentifier:(unsigned long long)arg10 vibrationIdentifier:(id)arg11 vibrationPattern:(id)arg12 ;
-(NSString *)alertTopic;
@end


@interface UNNotificationContent : NSObject 

@property (nonatomic,copy,readonly) NSArray * peopleIdentifiers;                           //@synthesize peopleIdentifiers=_peopleIdentifiers - In the implementation block
@property (nonatomic,readonly) BOOL hasDefaultAction;                                      //@synthesize hasDefautAction=_hasDefautAction - In the implementation block
@property (nonatomic,readonly) BOOL shouldAddToNotificationsList;                          //@synthesize shouldAddToNotificationsList=_shouldAddToNotificationsList - In the implementation block
@property (nonatomic,readonly) BOOL shouldAlwaysAlertWhileAppIsForeground;                 //@synthesize shouldAlwaysAlertWhileAppIsForeground=_shouldAlwaysAlertWhileAppIsForeground - In the implementation block
@property (nonatomic,readonly) BOOL shouldLockDevice;                                      //@synthesize shouldLockDevice=_shouldLockDevice - In the implementation block
@property (nonatomic,readonly) BOOL shouldPauseMedia;                                      //@synthesize shouldPauseMedia=_shouldPauseMedia - In the implementation block
@property (getter=isSnoozeable,nonatomic,readonly) BOOL snoozeable;                        //@synthesize snoozeable=_snoozeable - In the implementation block
@property (getter=isFromSnooze,nonatomic,readonly) BOOL fromSnooze;                        //@synthesize fromSnooze=_fromSnooze - In the implementation block
@property (nonatomic,copy,readonly) NSString * darwinNotificationName;                     //@synthesize darwinNotificationName=_darwinNotificationName - In the implementation block
@property (nonatomic,copy,readonly) NSString * darwinSnoozedNotificationName;              //@synthesize darwinSnoozedNotificationName=_darwinSnoozedNotificationName - In the implementation block
@property (nonatomic,copy,readonly) NSArray * attachments;                                 //@synthesize attachments=_attachments - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * badge;                                      //@synthesize badge=_badge - In the implementation block
@property (nonatomic,copy,readonly) NSString * body;                                       //@synthesize body=_body - In the implementation block
@property (nonatomic,copy,readonly) NSString * categoryIdentifier;                         //@synthesize categoryIdentifier=_categoryIdentifier - In the implementation block
@property (nonatomic,copy,readonly) NSString * launchImageName;                            //@synthesize launchImageName=_launchImageName - In the implementation block
@property (nonatomic,copy,readonly) UNNotificationSound * sound;                           //@synthesize sound=_sound - In the implementation block
@property (nonatomic,copy,readonly) NSString * subtitle; 
@property (nonatomic,copy,readonly) NSString * threadIdentifier;                           //@synthesize threadIdentifier=_threadIdentifier - In the implementation block
@property (nonatomic,copy,readonly) NSString * title;                                      //@synthesize title=_title - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * userInfo;                               //@synthesize userInfo=_userInfo - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSDictionary *)userInfo;
-(NSString *)title;
-(NSString *)body;
-(NSString *)subtitle;
-(BOOL)isFromSnooze;
-(NSString *)threadIdentifier;
-(UNNotificationSound *)sound;
-(NSString *)launchImageName;
-(NSString *)categoryIdentifier;
-(BOOL)isSnoozeable;
-(NSNumber *)badge;
-(NSString *)darwinNotificationName;
-(BOOL)shouldAlwaysAlertWhileAppIsForeground;
-(BOOL)hasDefaultAction;
-(BOOL)shouldLockDevice;
-(BOOL)shouldPauseMedia;
-(NSString *)darwinSnoozedNotificationName;
-(BOOL)shouldAddToNotificationsList;
-(NSArray *)attachments;
-(NSArray *)peopleIdentifiers;
-(id)_initWithAttachments:(id)arg1 badge:(id)arg2 body:(id)arg3 categoryIdentifier:(id)arg4 darwinNotificationName:(id)arg5 darwinSnoozedNotificationName:(id)arg6 fromSnooze:(BOOL)arg7 hasDefaultAction:(BOOL)arg8 launchImageName:(id)arg9 peopleIdentifiers:(id)arg10 shouldAddToNotificationsList:(BOOL)arg11 shouldAlwaysAlertWhileAppIsForeground:(BOOL)arg12 shouldLockDevice:(BOOL)arg13 shouldPauseMedia:(BOOL)arg14 snoozeable:(BOOL)arg15 sound:(id)arg16 subtitle:(id)arg17 threadIdentifier:(id)arg18 title:(id)arg19 userInfo:(id)arg20 ;
@end



@interface UNNotificationRequest : NSObject
@property (nonatomic,copy,readonly) NSString * identifier;                        //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,copy,readonly) UNNotificationContent * content;              //@synthesize content=_content - In the implementation block
@property (nonatomic,copy,readonly) UNNotificationTrigger * trigger;              //@synthesize trigger=_trigger - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)requestWithIdentifier:(id)arg1 content:(id)arg2 trigger:(id)arg3 ;
+(id)requestWithPushPayload:(id)arg1 bundleIdentifier:(id)arg2 ;
+(id)requestWithIdentifier:(id)arg1 pushPayload:(id)arg2 bundleIdentifier:(id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSString *)identifier;
-(UNNotificationContent *)content;
-(id)copyWithZone:(NSZone*)arg1 ;
-(UNNotificationTrigger *)trigger;
-(id)_initWithIdentifier:(id)arg1 content:(id)arg2 trigger:(id)arg3 ;
@end


@interface UNMutableNotificationContent : UNNotificationContent

@property (nonatomic,copy) NSArray * peopleIdentifiers; 
@property (assign,nonatomic) BOOL hasDefaultAction; 
@property (assign,nonatomic) BOOL shouldAddToNotificationsList; 
@property (assign,nonatomic) BOOL shouldAlwaysAlertWhileAppIsForeground; 
@property (assign,nonatomic) BOOL shouldLockDevice; 
@property (assign,nonatomic) BOOL shouldPauseMedia; 
@property (assign,getter=isSnoozeable,nonatomic) BOOL snoozeable; 
@property (assign,getter=isFromSnooze,nonatomic) BOOL fromSnooze; 
@property (nonatomic,copy) NSString * darwinNotificationName; 
@property (nonatomic,copy) NSString * darwinSnoozedNotificationName; 
@property (nonatomic,copy) NSArray * attachments; 
@property (nonatomic,copy) NSNumber * badge; 
@property (nonatomic,copy) NSString * body; 
@property (nonatomic,copy) NSString * categoryIdentifier; 
@property (nonatomic,copy) NSString * launchImageName; 
@property (nonatomic,copy) UNNotificationSound * sound; 
@property (nonatomic,copy) NSString * subtitle; 
@property (nonatomic,copy) NSString * threadIdentifier; 
@property (nonatomic,copy) NSString * title; 
@property (nonatomic,copy) NSDictionary * userInfo; 
-(void)setTitle:(NSString *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(void)setSubtitle:(NSString *)arg1 ;
-(void)setBadge:(NSNumber *)arg1 ;
-(void)setBody:(NSString *)arg1 ;
-(void)setCategoryIdentifier:(NSString *)arg1 ;
-(void)setHasDefaultAction:(BOOL)arg1 ;
-(void)setLaunchImageName:(NSString *)arg1 ;
-(void)setShouldAddToNotificationsList:(BOOL)arg1 ;
-(void)setShouldAlwaysAlertWhileAppIsForeground:(BOOL)arg1 ;
-(void)setShouldLockDevice:(BOOL)arg1 ;
-(void)setShouldPauseMedia:(BOOL)arg1 ;
-(void)setSnoozeable:(BOOL)arg1 ;
-(void)setFromSnooze:(BOOL)arg1 ;
-(void)setDarwinNotificationName:(NSString *)arg1 ;
-(void)setDarwinSnoozedNotificationName:(NSString *)arg1 ;
-(void)setSound:(UNNotificationSound *)arg1 ;
-(void)setThreadIdentifier:(NSString *)arg1 ;
-(void)setAttachments:(NSArray *)arg1 ;
-(void)setPeopleIdentifiers:(NSArray *)arg1 ;
@end

@interface UNTimeIntervalNotificationTrigger : UNNotificationTrigger

@property (nonatomic,readonly) double timeInterval;              //@synthesize timeInterval=_timeInterval - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)triggerWithTimeInterval:(double)arg1 repeats:(BOOL)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(double)timeInterval;
-(id)nextTriggerDateAfterDate:(id)arg1 withRequestedDate:(id)arg2 ;
-(id)nextTriggerDate;
-(id)_initWithTimeInterval:(double)arg1 repeats:(BOOL)arg2 ;
@end

